### ISSUE TITLE
Provide node to other langagues

### ISSUE THREAD

**Issue by marianacastan** [GoogleCloudPlatform/node-red-contrib-google-cloud#28]
Can't change the default language en-US to another that is already supported by Google API. Only changing at .json and .js files at /node_modules from en-US to es-ES can't help...it just recognizes english. Creating a field with language option would be very helpfull for the community

**Comment by kolban-google** [comment]
Sorry for the delay.  Apparently I hadn't set up my auto subscription correctly.  Examining issue now.  Thank you for raising.  I'll post back as soon as possible.

**Comment by kolban-google** [comment]
I think I have coded the change correctly.  The Speech to Text node now has a configuration property that allows us to specify a language code.  The default becomes en-US but can now be changed.  For example, changing en-US to en-ES should now work.  I haven't tested it with a language other than English so if I can ask ... would you test and report back if it works?  Releases of this node set at 0.0.7 or greater will contain the change.

**Comment by marianacastan** [comment]
Just tested and it works perfectly! Thank you a lot!

**Comment by kolban-google** [comment]
Thank you Mariana.  Appreciate the report and sorry it too me so long.  Don't hesitate to post anything else as you find ... especially if there are features you would like.  I'll be quicker.  Closing the issue for just now.
