### ISSUE TITLE
Specify a file name in the configuration for GCS Write

### ISSUE THREAD

**Issue by kolban-google** [GoogleCloudPlatform/node-red-contrib-google-cloud#3]
Currently, when we use the GCS Write node, we expect to find a file name in the msg.filename property at runtime.  While this is great, we can do more.  This issue suggests a new feature that provides an optional file name in the configuration properties for the node.  The suggested semantics are:

* If msg.filename exists ... use it
* if msg.filename does NOT exist then use the configured filename supplied by the flow designer
* If neither msg.filename nor a configured filename exist, then that would be an error.

**Comment by kolban-google** [comment]
The code changes have been made and pushed to the `dev` branch.  This issue will be closed once published for download.

**Comment by profDgasca** [comment]
Hi,
I try to create a new jpg file from node-red in a raspi, mi npm version is 6.4.1
my configuration is:
msg = {
    filename:'gs://bucket/test.jpg', 
    payload:msg.payload,
    contentType:'image/jpeg'
}
where
msg.payload is a buffer

The error is:
**TypeError: Cannot read property 'ending' of undefined**

It's somthing wrong with my config?
thanks a lot and regrads
