### ISSUE TITLE
Firestore probrem mode:set, update, delete, get

### ISSUE THREAD

**Issue by maskoba** [GoogleCloudPlatform/node-red-contrib-google-cloud#57]
I have installed Firestore in Node-RED.
But except mode:query, unsuccessfully.

The path to the document see below.
msg.payload.path = /collection/document

ex
if (mode == 'set' || mode == 'update' || mode == 'delete' || mode == 'get') {
const document = firestore.doc(msg.payload.path);
}

Help would be much appreciated. Thanks

**Comment by kolban-google** [comment]
Hello my friend.  Would you be able to share with me an example flow that is failing?  What exact errors or symptoms are you seeing?  My plan is to try and recreate.  If there are associated logs showing error symptoms, those would be great to see too.

**Comment by maskoba** [comment]
Hi, kolban

mode:get 
<img width="667" alt="スクリーンショット 2020-03-02 18 02 31" src="https://user-images.githubusercontent.com/17641618/75663523-4a619800-5cb4-11ea-9da2-04690b16ad8c.png">
**debug screen No Errors**
<img width="304" alt="スクリーンショット 2020-03-02 18 24 33" src="https://user-images.githubusercontent.com/17641618/75663591-6cf3b100-5cb4-11ea-9e78-b21774ded0f4.png">
**property Get-Inject**
<img width="485" alt="スクリーンショット 2020-03-02 18 24 57" src="https://user-images.githubusercontent.com/17641618/75663758-b17f4c80-5cb4-11ea-87cd-324ad59c86cd.png">
**property Get-ChangeNode**
<img width="494" alt="スクリーンショット 2020-03-02 18 25 36" src="https://user-images.githubusercontent.com/17641618/75663807-c5c34980-5cb4-11ea-8ede-2084c6772300.png">

Thanks

**Comment by kolban-google** [comment]
Thank you my friend.  I have all the information I need to start investigation.  I will start looking in depth now and will report back with updates as and when I come to them.

**Comment by kolban-google** [comment]
Wow ... gosh.  I found at least two major errors.  Thankfully they were easily cured.  At this point, I can refresh the build but what I'd really like to do is give you a patch and have you test it for me.  I am not sure how familiar you are with Node-RED nor how you are running your Node-RED environment.  When you install the node-red-contrib-google-cloud package, it installs a bunch of Node.js files.  One of those files is called "firestore.js".  Here is a link to a paste of a patched version:

https://pastebin.com/AWXxtbQg

In an ideal world, I would like to ask you to find your existing firestore.js from the package and replace the content with the paste above and then re-test and see if that fixes the issue. If it does then I will publish the patch and refresh the Node-RED repository.

I realize I am asking you to do work here and if you don't know how or you simply choose not to, that will be fine.  Just post back and let me know and I'll refresh the Node-RED repository immediately.  My desire is to have you test and once YOU are satisfied, then I would republish for all.  If you test and you are not satisfied, then we haven't caused others to refresh too soon.

**Comment by maskoba** [comment]
I'm using GCP container-image to run Node-RED, so please release an update.
Thanks

**Comment by kolban-google** [comment]
Howdy my friend.  I have committed and pushed a refresh which contains the changes.  This should be available as the package at 0.0.14 or above.  Please refresh and test and post back when you can.  Hopefully this is the fix but if ANYTHING is still amiss, I'll be delighted to assist.

**Comment by maskoba** [comment]
Confirmed all the following features of Firestore
set, get, update, delete, query
Please close this issue
Thank you

**Comment by kolban-google** [comment]
That is great news and THANK YOU for reporting and giving feedback.  Apologies for the problem in the first place.  If ever you have new issues, PLEASE feel very welcome to raise them here and we will get to them as quickly as you can.  Thank you for using GCP functions.
