### ISSUE TITLE
pubsub node bug

### ISSUE THREAD

**Issue by MiLaak** [GoogleCloudPlatform/node-red-contrib-google-cloud#59]
There is minor bug in pubsub node. If using "Assume JSON" option and the received pubsub message is not valid JSON then there will be uncaughtException and whole node red will shut down. ref https://nodered.org/docs/user-guide/handling-errors

Work around is simple: Not to use "Assume JSON" but instead parse JSON on separate node.

**Comment by kolban-google** [comment]
Delivered as part of 0.0.15
