### ISSUE TITLE
Examination of an AutoML node

### ISSUE THREAD

**Issue by kolban-google** [GoogleCloudPlatform/node-red-contrib-google-cloud#73]
A user wishes to use AutoML capabilities and has given us a sample of a GCP REST API they would like to use.  We are now examining what a generic node would look like.

Here is some code they are using today:

```
jQuery.ajax({
    url: "https://eu-automl.googleapis.com/v1/projects/1234/locations/eu/models/1234:predict",
    type: "POST",
    headers: {
        "Content-Type": "text/plain; charset=utf-8",
    },
    processData: false,
    data: "{
  \"payload\": {
    \"textSnippet\": {
      \"content\": \"some text\",
      \"mime_type\": \"text/plain\"
    }
  }
}",
})
```

**Comment by kolban-google** [comment]
The API looks pretty straightforward.  See:

https://cloud.google.com/natural-language/automl/docs/libraries/client-libraries#client-libraries-nodejs

From this, it looks like we can wrap into a simple call as found here:

https://googleapis.dev/nodejs/automl/latest/index.html

by calling the `predict` API.

https://googleapis.dev/nodejs/automl/latest/v1beta1.PredictionServiceClient.html#predict.

While this looks easy to code up, the first thing I need to find is a sample that I can test against to ensure that it is working.  It is tempting to code it up and then release it but without testing, that would be a poor story.

**Comment by d0hnj0e** [comment]
If you want to use a custom trained model from me for testing, just let me know! :)

**Comment by kolban-google** [comment]
A release (0.0.18) has been pushed that includes the AutoML function.  Looking to the requestor to see how close we are to what is needed.

**Comment by kolban-google** [comment]
Solution shipped and accepted by consumer.
